import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/common/header";
import Image from "next/image";
import koleshwarDhamTextLogo from "@/assets/images/Shree.png";
import Footer from "@/components/common/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-white w-full flex justify-between p-2 ">
          <div className="flex gap-2">
            <div
              className="flex items-center justify-center rounded-full
              bg-white border h-[3rem]  w-[3rem] lg:h-[4rem] lg:w-[4rem] drop-shadow-lg"
            >
              <img
                src="https://www.khodaldhamtrust.org/upload_data/general/5dfbcbd162bff_jay-khodiyar.png"
                className="h-full w-full object-contain"
              />
            </div>
            <div className=" h-[3rem]  lg:h-[4rem] ">
              <img src={koleshwarDhamTextLogo.src} className="h-full" />
            </div>
          </div>
          <div className="flex gap-3">
            <div
              className="flex items-center justify-center rounded-full
              bg-white border  h-[3rem]  w-[3rem] lg:h-[4rem] lg:w-[4rem] drop-shadow-lg"
            >
              <img
                src="https://www.khodaldhamtrust.org/upload_data/general/5dfbcbd162bff_jay-khodiyar.png"
                className="h-full w-full object-contain"
              />
            </div>
            <div
              className="flex items-center justify-center rounded-full
              bg-white border  h-[3rem]  w-[3rem] lg:h-[4rem] lg:w-[4rem] drop-shadow-lg"
            >
              <img
                src="https://www.khodaldhamtrust.org/upload_data/general/5dfbcbd162bff_jay-khodiyar.png"
                className="h-full w-full object-contain"
              />
            </div>
          </div>
        </div>
        <header className="sticky top-0 z-50">
          <Header />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
